### ISSUE TITLE
🐛 Bug ➾ minting is failing to find the contract in NFT Scaffold

### ISSUE THREAD

**Issue by michaelkernaghan** [ecadlabs/taqueria#1442]
### 🚥 Status (Internal Taqueria Team Use Only)

- [ ] 🔬 Investigated and Verified
- [ ] ⚗️ Solution Identified and Designed 
- [ ] 🧫 Dev Implementation of Fix
- [ ] 🧪 Fix Tested and Validated
- [ ] 🏆 PR Merged

### 🆘 What happened?

I run through the instructions for the NFT scaffold and set up the project fine. Everything works except the minting step, which throws an error that it cannot find the contract. I note as well on the UI that the contract is not listed.

### 🆘 Steps to Reproduce?

1. taq scaffold https://github.com/ecadlabs/taqueria-scaffold-nft nft-scaffold
2. cd nft-scaffold
3. npm run setup
4. cd taqueria
5. touch .env
6. Get your Pinata JWT token from your Pinata account
7. Insert the JWT from Pinata into the .env file echo “pinataJwtToken=eyJhbGc…” >> .env
8. cd …
9. npm run start:taqueria:local
10. npm run apply
11. There is an error in the storage contract:
````
▶ run 'compile contract'
runTask: taq compile main.mligo

=== For main.storages.mligo ===
File "contracts/main.storages.mligo", line 3, character 28 to line 10, character 1:
  2 | 
  3 | let init_storage: storage = { 
  4 |     ledger = (Big_map.empty: ledger);
  5 |     operators = (Big_map.empty: (operator, unit) big_map);
  6 |     metadata = (Big_map.empty: (string, bytes) big_map);
  7 |     token_metadata = (Big_map.empty: (token_id, token_metadata) big_map);
  8 |     total_supply = 0n;
  9 |     admin = ("tz1KqTpEZ7Yob7QbPE4Hy4Wo8fHG8LhKxZSx" : address)
 10 | }

Mismatching record labels. Expected record of type record[admin -> address , ledger -> big_map (( address * nat ) , nat) , metadata -> big_map (string , bytes) , operators -> big_map (record[operator -> address , owner -> address , token_id -> nat] , unit) , paused -> bool , token_metadata -> big_map (nat , record[token_id -> nat , token_info -> map (string , bytes)]) , total_supply -> nat].
```
it appears to work, but when you then add assets and run apply again, you get an error
```
 taqueria-scaffold-nft@1.0.0 apply
> cd ./taqueria && npx ts-node ./provisioning/mock-provisioner-runner.ts --apply

/home/michael/nft-scaffold/node_modules/ts-node/src/index.ts:843
    return new TSError(diagnosticText, diagnosticCodes, diagnostics);
           ^
TSError: ⨯ Unable to compile TypeScript:
provisioning/taquito-access.ts:47:13 - error TS2741: Property 'paused' is missing in type '{ admin: address; ledger: BigMap<{ 0: address; 1: nat; }, never>; metadata: BigMap<string, bytes>; operators: BigMap<{ owner: address; operator: address; token_id: nat; }, never>; token_metadata: BigMap<...>; total_supply: nat; }' but required in type 'Storage'.

47             storage: {
               ~~~~~~~

  types/main.types.ts:17:5
    17     paused: boolean;
           ~~~~~~
    'paused' is declared here.
  node_modules/@taquito/taquito/dist/types/operations/types.d.ts:79:5
    79     storage?: never;
           ~~~~~~~
    The expected type comes from property 'storage' which is declared here on type 'OriginateParams<Storage>'

    at createTSError (/home/michael/nft-scaffold/node_modules/ts-node/src/index.ts:843:12)
    at reportTSError (/home/michael/nft-scaffold/node_modules/ts-node/src/index.ts:847:19)
    at getOutput (/home/michael/nft-scaffold/node_modules/ts-node/src/index.ts:1057:36)
    at Object.compile (/home/michael/nft-scaffold/node_modules/ts-node/src/index.ts:1411:41)
    at Module.m._compile (/home/michael/nft-scaffold/node_modules/ts-node/src/index.ts:1596:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.require.extensions.<computed> [as .ts] (/home/michael/nft-scaffold/node_modules/ts-node/src/index.ts:1600:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  diagnosticCodes: [ 2741 ]
}
```
### 🪵 Relevant log output


### 🐘 How impactful is this bug?

🚒 Showstopper

### ⏱️ Prevalance

everytime

### 💻 Operating System

Windows -> Linux VM

### 🕸️ System Architecture

_No response_

### 🌮 Taqueria Version

v0.22.0

### 🌿 Node.js Version

v18.4.0

### ☎️ Contact Details

michaelkernaghan@ecadlabs.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by michaelkernaghan** [comment]
I believe Claude has fixed the contract

**Comment by claudebarde** [comment]
The `paused` property was missing in the Ligo storage, you should add it in the JavaScript code as well

**Comment by hu3man** [comment]
Great, can this be closed now?

**Comment by hu3man** [comment]
@claudebarde ?

**Comment by michaelkernaghan** [comment]
I'll check this out and update this issue when I go through it again for ^0.23

**Comment by michaelkernaghan** [comment]
The nft scaffold still has this problem in the 0.23 pre release.
please fix :)

**Comment by claudebarde** [comment]
This issue was fixed in this pull request: https://github.com/ecadlabs/taqueria-scaffold-nft/pull/13/
I also added tests I wrote in Ligo for review.

**Comment by hu3man** [comment]
Great, just 2 small things to address on that PR and then let's merge
