### ISSUE TITLE
🐛 Bug ➾ Taco Shop Scaffold crashes when starting development server

### ISSUE THREAD

**Issue by michaelkernaghan** [ecadlabs/taqueria#1651]
### 🚥 Status (Internal Taqueria Team Use Only)

- [ ] 🔬 Investigated and Verified
- [ ] ⚗️ Solution Identified and Designed 
- [ ] 🧫 Dev Implementation of Fix
- [ ] 🧪 Fix Tested and Validated
- [ ] 🏆 PR Merged

### 🆘 What happened?

I was following through the Taco Shop Scaffold demo, using the steps on the Live docs website, and using an isolated Linux machine used only for acceptance testing from product releases, and when I did step 4, there was a crash,

### 🆘 Steps to Reproduce?

1. taq scaffold https://github.com/ecadlabs/taqueria-scaffold-taco-shop taco-shop
2. cd taco-shop
3. npm run setup
4. npm run start:app
5. Starting the development server...
Error: error:0308010C:digital envelope routines::unsupported

### 🪵 Relevant log output

```shell
Starting the development server...

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/home/mike/taco-shop/app/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/mike/taco-shop/app/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/mike/taco-shop/app/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/mike/taco-shop/app/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/mike/taco-shop/app/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/mike/taco-shop/app/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/mike/taco-shop/app/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/home/mike/taco-shop/app/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
/home/mike/taco-shop/app/node_modules/react-scripts/scripts/start.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/home/mike/taco-shop/app/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/mike/taco-shop/app/node_modules/webpack/lib/NormalModule.js:417:16)
    at /home/mike/taco-shop/app/node_modules/webpack/lib/NormalModule.js:452:10
    at /home/mike/taco-shop/app/node_modules/webpack/lib/NormalModule.js:323:13
    at /home/mike/taco-shop/app/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /home/mike/taco-shop/app/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/home/mike/taco-shop/app/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /home/mike/taco-shop/app/node_modules/babel-loader/lib/index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.4.0
```

### 🐘 How impactful is this bug?

🚒 Showstopper

### ⏱️ Prevalance

everytime

### 💻 Operating System

Windows -> Linux VM

### 🕸️ System Architecture

x64

### 🌮 Taqueria Version

v0.24.2

### 🌿 Node.js Version

 v18.4.0

### ☎️ Contact Details

michaelkernaghan@ecadlabs.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by acharlop** [comment]
This is a bug due to Node 18. If you downgrade to Node.js 16 it works

**Comment by mweichert** [comment]
Cannot reproduce
