### ISSUE TITLE
Bug:  Cannot find module '@taqueria/protocol/out/types/Alias' from 'taqueria-protocol/Alias.js'

### ISSUE THREAD

**Issue by mweichert** [ecadlabs/taqueria#1775]
3 different people have encountered this issue when attempting to run taqueria-sdk unit tests:

```
 Cannot find module '@taqueria/protocol/out/types/Alias' from 'taqueria-protocol/Alias.js'
```

I think it might be related to the package-lock.json, but it's just a guess at this point.

As of Jan 17th, Michal and Houston both have this problem and can reproduce.

I had this problem, but managed to fix it - although I'm not 100% sure how. I think it was a matter of reverting changes to the package-lock.json.

**Comment by mweichert** [comment]
Relevant output:
```
 @taqueria/tests@0.25.25-rc test:unit:jest
> ../bin/before-all-tests.sh && TEST=true jest --config jest.config.unit.ts --no-cache

There are no docker containers to remove
FAIL unit/taqueria-sdk/taqueria-sdk.spec.ts
  ● Test suite failed to run

    Cannot find module '@taqueria/protocol/out/types/Alias' from 'taqueria-protocol/Alias.js'

    Require stack:
      taqueria-protocol/Alias.js
      taqueria-protocol/index.js
      taqueria-sdk/index.js
      tests/unit/taqueria-sdk/taqueria-sdk.spec.ts

    > 1 | export * from '@taqueria/protocol/out/types/Alias';
        |               ^
      2 |

      at Resolver._throwModNotFoundError (tests/node_modules/jest-resolve/build/resolver.js:425:11)
      at Object.<anonymous> (taqueria-protocol/Alias.ts:1:15)
      at Object.<anonymous> (taqueria-protocol/index.ts:1:24)
      at Object.<anonymous> (taqueria-sdk/index.ts:2:27)
      at Object.<anonymous> (tests/unit/taqueria-sdk/taqueria-sdk.spec.ts:1:1)
```

**Comment by mweichert** [comment]
Can no longer reproduce.
