### ISSUE TITLE
🐛 Bug ➾ taq clean gets zod error

### ISSUE THREAD

**Issue by michaelkernaghan** [ecadlabs/taqueria#1834]
### 🚥 Status (Internal Taqueria Team Use Only)

- [ ] 🔬 Investigated and Verified
- [ ] ⚗️ Solution Identified and Designed 
- [ ] 🧫 Dev Implementation of Fix
- [ ] 🧪 Fix Tested and Validated
- [ ] 🏆 PR Merged

### 🆘 What happened?

try t run taq clean on production release install and it gets zod error

### 🆘 Steps to Reproduce?

1. install taq from release v0.28.0
2. init a project and cd to it
3. taq clean
4. zod

### 🪵 Relevant log output

```shell
❯ taq clean
E_PARSE: The plugin request arguments are invalid
    at /home/mike/taco-shop/node_modules/@taqueria/node-sdk/index.js:139:39
    at call (/home/mike/taco-shop/node_modules/fluture/index.cjs:139:31)
    at Transformation.MapRejTransformation$rejected (/home/mike/taco-shop/node_modules/fluture/index.cjs:1491:39)
    at Transformation.transformationHandler [as rejected] (/home/mike/taco-shop/node_modules/fluture/index.cjs:743:21)
    at rejected (/home/mike/taco-shop/node_modules/fluture/index.cjs:615:29)
    at Interpreter.Reject$interpret [as _interpret] (/home/mike/taco-shop/node_modules/fluture/index.cjs:528:5)
    at drain (/home/mike/taco-shop/node_modules/fluture/index.cjs:682:27)
    at settle (/home/mike/taco-shop/node_modules/fluture/index.cjs:608:17)
    at Interpreter.Transformer$interpret [as _interpret] (/home/mike/taco-shop/node_modules/fluture/index.cjs:695:5)
    at promise$computation (/home/mike/taco-shop/node_modules/fluture/index.cjs:1721:9) {
  context: [
    '/home/mike/.nvm/versions/node/v16.19.0/bin/node',
    '/home/mike/taco-shop/node_modules/@taqueria/plugin-taquito/index.js',
    '--taqRun',
    'pluginInfo',
    '--i18n',
    '{}',
    '--config',
    '{"language":"en","artifactsDir":"artifacts","contractsDir":"contracts","plugins":[{"type":"npm","name":"@taqueria/plugin-ligo"},{"type":"npm","name":"@taqueria/plugin-flextesa"},{"type":"npm","name":"@taqueria/plugin-taquito"},{"type":"npm","name":"@taqueria/plugin-jest"}],"accounts":{"bob":"3_000_000_000","alice":"3_000_000_000","john":"3_000_000_000","jane":"3_000_000_000","joe":"3_000_000_000"},"environment":{"default":"testing","development":{"networks":[],"sandboxes":["local-scaffold"],"storage":{}},"testing":{"networks":["ghostnet"],"sandboxes":[],"aliases":{"hello-tacos":{"address":"KT1LMNSCTCprDtuzAJ5GiAHNdC1r5q8qiZYc"}}}},"network":{"ghostnet":{"label":"ghostnet","rpcUrl":"https://ghostnet.ecadinfra.com"}},"sandbox":{"local-scaffold":{"label":"Local Tezos Sandbox","rpcUrl":"http://localhost:21000","protocol":"PtKathmankSpLLDALzWw7CGD2j2MtyveTwboEYokqUCP4a1LxMg"}},"projectDir":"/home/mike/taco-shop","configFile":"/home/mike/taco-shop/.taq/config.json","hash":"f40b73d9d2f2169bae95736d0c20289d8bfcd8ccaa6c3e8a80c1c3fd83e22af2"}',
    '--envVars',
    '{}',
    '_',
    'clean',
    '--maxConcurrency',
    '10',
    '--debug',
    'false',
    '--disableState',
    'false',
    '--logPluginRequests',
    'false',
    '--fromVsCode',
    'false',
    '--version',
    'false',
    '--build',
    'false',
    '--help',
    'false',
    '--yes',
    'false',
    '--setBuild',
    '7673210',
    '--setVersion',
    'v0.28.0',
    '--lock',
    './deno-lock.json',
    '--target',
    'x86_64-unknown-linux-gnu',
    '--d',
    'false',
    '--projectDir',
    '/home/mike/taco-shop'
  ],
  kind: 'E_PARSE',
  previous: ZodError: [
    {
      "code": "invalid_type",
      "expected": "string",
      "received": "undefined",
      "path": [
        "config",
        "network",
        "ghostnet",
        "protocol"
      ],
      "message": "Required"
    }
  ]
      at handleResult (/home/mike/taco-shop/node_modules/zod/lib/types.js:29:23)
      at ZodEffects.safeParse (/home/mike/taco-shop/node_modules/zod/lib/types.js:142:16)
      at ZodEffects.parse (/home/mike/taco-shop/node_modules/zod/lib/types.js:122:29)
      at Object.from (/home/mike/taco-shop/node_modules/@taqueria/protocol/Base.js:65:42)
      at parseArgs (/home/mike/taco-shop/node_modules/@taqueria/node-sdk/index.js:236:40)
      at Object.create (/home/mike/taco-shop/node_modules/@taqueria/node-sdk/index.js:562:12)
      at Object.<anonymous> (/home/mike/taco-shop/node_modules/@taqueria/plugin-taquito/index.js:335:36)
      at Module._compile (node:internal/modules/cjs/loader:1165:14)
      at Object.Module._extensions..js (node:internal/modules/cjs/loader:1219:10)
      at Module.load (node:internal/modules/cjs/loader:1043:32) {
    issues: [ [Object] ],
    addIssue: [Function (anonymous)],
    addIssues: [Function (anonymous)],
    errors: [ [Object] ]
  }
}
taq [command]

Commands:
  taq init [projectDir]                     Initialize a new project
  taq scaffold [scaffoldUrl] [scaffoldProj  Generate a new project using pre-mad
  ectDir]                                   e scaffold
  taq opt-in                                Opt-in to sharing anonymous usage an
                                            alytics
  taq opt-out                               Opt-out of sharing anonymous usage a
                                            nalytics

Options:
  -p, --projectDir  Path to your project directory               [default: "./"]
  -e, --env         Specify an environment configuration
      --version     Show version number                                [boolean]
      --build       Display build information about the current version[boolean]

Please be advised that Taqueria is currently in BETA.

The @taqueria/plugin-taquito plugin experienced an error when getting information about the @taqueria/plugin-taquito plugin.
```

### 🐘 How impactful is this bug?

🤔 Notable but managable

### ⏱️ Prevalance

everytime

### 💻 Operating System

Windows -> Linux VM

### 🕸️ System Architecture

arm64 (M1 Macs)

### 🌮 Taqueria Version

0.28.0

### 🌿 Node.js Version

v16.16.0

### ☎️ Contact Details

michaelkernaghan@ecadlabs.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by michaelkernaghan** [comment]
my bad ooops it was an olf project made from taco shop scaffold.
