### ISSUE TITLE
Add test(s) to verify project scaffolding functionality

### ISSUE THREAD

**Issue by sinapsist** [ecadlabs/taqueria#354]
As an SDET I want to add tests to cover the project scaffolding feature (more details can be found here. -https://github.com/ecadlabs/taqueria/issues/128)

More details about the approach:
1. Verify folder structure (manually need to clone the repo and manually generate hash sum)
https://github.com/ecadlabs/taqueria-scaffold-quickstart
Steps to implement (need to implement once to have initial structure and place it under data folder:
    1. git clone
    2. rm .taq/scaffold.json
    3. rm .git
    4. npm install
2. Verify hash sum and project structure
    1. which to compare data/scaffold and project that we are getting from taq scaffold
    
AC: Test(s) to verify scaffolding feature

**Comment by hu3man** [comment]
@sinapsist , here is the log output for the failing test on my machine:
```
taqueria/tests on  main 3s 
❯ npm run test:e2e        

> @taqueria/tests@0.2.1 test:e2e
> jest --config jest.config.e2e.ts

 PASS  e2e/taqueria-cli-init.spec.ts
 FAIL  e2e/taqueria-cli-scaffolding-functional.spec.ts
  ● E2E Testing for taqueria scaffolding initialization, › Verify that scaffold project can be set up

    error: Error: Command failed: cd taqueria-quickstart && npm run setup
    npm ERR! Missing script: "setup"
    npm ERR! 
    npm ERR! To see a list of scripts, run:
    npm ERR!   npm run

    npm ERR! A complete log of this run can be found in:
    npm ERR!     /Users/houstonkrohman/.npm/_logs/2022-04-28T17_32_00_070Z-debug-0.log

      13 |             await exec(`cd ${scaffoldDirName} && npm run setup`)
      14 |         } catch (error) {
    > 15 |             throw new Error (`error: ${error}`)
         |                   ^
      16 |         }
      17 |     })
      18 |

      at e2e/taqueria-cli-scaffolding-functional.spec.ts:15:19
      at step (e2e/taqueria-cli-scaffolding-functional.spec.ts:33:23)
      at Object.throw (e2e/taqueria-cli-scaffolding-functional.spec.ts:14:53)
      at rejected (e2e/taqueria-cli-scaffolding-functional.spec.ts:6:65)

  ● E2E Testing for taqueria scaffolding initialization, › Verify that scaffold project can build taqueria

    error: Error: Command failed: cd taqueria-quickstart && npm run setup
    npm ERR! Missing script: "setup"
    npm ERR! 
    npm ERR! To see a list of scripts, run:
    npm ERR!   npm run

    npm ERR! A complete log of this run can be found in:
    npm ERR!     /Users/houstonkrohman/.npm/_logs/2022-04-28T17_32_00_070Z-debug-0.log

      13 |             await exec(`cd ${scaffoldDirName} && npm run setup`)
      14 |         } catch (error) {
    > 15 |             throw new Error (`error: ${error}`)
         |                   ^
      16 |         }
      17 |     })
      18 |

      at e2e/taqueria-cli-scaffolding-functional.spec.ts:15:19
      at step (e2e/taqueria-cli-scaffolding-functional.spec.ts:33:23)
      at Object.throw (e2e/taqueria-cli-scaffolding-functional.spec.ts:14:53)
      at rejected (e2e/taqueria-cli-scaffolding-functional.spec.ts:6:65)

  ● E2E Testing for taqueria scaffolding initialization, › Verify that scaffold project can start and stop taqueria locally

    error: Error: Command failed: cd taqueria-quickstart && npm run setup
    npm ERR! Missing script: "setup"
    npm ERR! 
    npm ERR! To see a list of scripts, run:
    npm ERR!   npm run

    npm ERR! A complete log of this run can be found in:
    npm ERR!     /Users/houstonkrohman/.npm/_logs/2022-04-28T17_32_00_070Z-debug-0.log

      13 |             await exec(`cd ${scaffoldDirName} && npm run setup`)
      14 |         } catch (error) {
    > 15 |             throw new Error (`error: ${error}`)
         |                   ^
      16 |         }
      17 |     })
      18 |

      at e2e/taqueria-cli-scaffolding-functional.spec.ts:15:19
      at step (e2e/taqueria-cli-scaffolding-functional.spec.ts:33:23)
      at Object.throw (e2e/taqueria-cli-scaffolding-functional.spec.ts:14:53)
      at rejected (e2e/taqueria-cli-scaffolding-functional.spec.ts:6:65)

 FAIL  e2e/taqueria-cli-scaffolding-init.spec.ts (5.463 s)
  ● E2E Testing for taqueria scaffolding initialization, › Verify that taq scaffold quickstart project has the correct file structure

    error: Error: Command failed: ls taqueria-quickstart
    ls: taqueria-quickstart: No such file or directory

      33 |             await fsPromises.rm(`./${scaffoldDirName}`, { recursive: true })
      34 |         } catch(error) {
    > 35 |             throw new Error (`error: ${error}`)
         |                   ^
      36 |         }
      37 |     })
      38 |

      at e2e/taqueria-cli-scaffolding-init.spec.ts:35:19
      at step (e2e/taqueria-cli-scaffolding-init.spec.ts:33:23)
      at Object.throw (e2e/taqueria-cli-scaffolding-init.spec.ts:14:53)
      at rejected (e2e/taqueria-cli-scaffolding-init.spec.ts:6:65)

  ● E2E Testing for taqueria scaffolding initialization, › Verify that taq scaffold can use the URL parameter to clone a different scaffold into the project

    error: Error: expect(received).toContain(expected) // indexOf

    Expected substring: "README.md"
    Received string:    "package-lock.json
    "

      69 |             await fsPromises.rm(`./${scaffoldDirName}`, { recursive: true })
      70 |         } catch(error) {
    > 71 |             throw new Error (`error: ${error}`)
         |                   ^
      72 |         }
      73 |     })
      74 |

      at e2e/taqueria-cli-scaffolding-init.spec.ts:71:19
      at step (e2e/taqueria-cli-scaffolding-init.spec.ts:33:23)
      at Object.next (e2e/taqueria-cli-scaffolding-init.spec.ts:14:53)
      at fulfilled (e2e/taqueria-cli-scaffolding-init.spec.ts:5:58)

  ● E2E Testing for taqueria scaffolding initialization, › Verify that taq scaffold returns an error with a bogus URL

    error: Error: expect(received).toContain(expected) // indexOf

    Expected substring: "GIT_CLONE_FAILED"
    Received string:    "{
      kind: \"E_INVALID_PATH_ALREADY_EXISTS\",
      msg: \"Path already exists\",
      context: \"/Users/houstonkrohman/code/taqueria/tests/taqueria-quickstart\"
    }
    "

      81 |
      82 |         } catch(error) {
    > 83 |             throw new Error (`error: ${error}`)
         |                   ^
      84 |         }
      85 |     })
      86 |

      at e2e/taqueria-cli-scaffolding-init.spec.ts:83:19
      at step (e2e/taqueria-cli-scaffolding-init.spec.ts:33:23)
      at Object.next (e2e/taqueria-cli-scaffolding-init.spec.ts:14:53)
      at fulfilled (e2e/taqueria-cli-scaffolding-init.spec.ts:5:58)

(node:30542) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
 PASS  e2e/taqueria-plugin-contract-types.spec.ts (12.156 s)
 PASS  e2e/taqueria-plugin-archetype.spec.ts (12.667 s)
 PASS  e2e/taqueria-plugin-ligo.spec.ts (14.571 s)
 PASS  e2e/taqueria-cli-commands.spec.ts (50.756 s)
 PASS  e2e/taqueria-plugin-flextesa.spec.ts (71.207 s)
 PASS  e2e/taqueria-plugin-taquito.spec.ts (151.5 s)

Test Suites: 2 failed, 7 passed, 9 total
Tests:       6 failed, 7 skipped, 68 passed, 81 total
Snapshots:   0 total
Time:        151.807 s
Ran all test suites.
```

**Comment by hu3man** [comment]
@alexzbusko @sinapsist, just wanted to confirm where we are at with this ticket (blocked/under investigation/in progress) and steps forward for this iteration

On slack it sounded like we are thinking this is a Mac issue that only affects local e2e testing. If that's the case, we should decide whether it's worth continuing to investigate/fix or to defer to after M2

**Comment by alexzbusko** [comment]
@hu3man I think @sinapsist is the person to answer that question. If we choose to defer it I think having some kind of warning that it may affect mac users should be sufficient
