### ISSUE TITLE
[Bug]: Deploying multiple contracts can fail

### ISSUE THREAD

**Issue by mweichert** [ecadlabs/taqueria#512]
### What happened?

If someone executes `taq originate`, we will deploy all contracts from the artifacts directory. We do this by using Taquito's contract.originate() method. We currently do this sequentially, which can cause problems, and in particular on testnets.

Lets say that there are two contracts to deploy, A and B. The operation for originating contract A is sent to the node with a particular counter, such as 1000. The operation for deploying contract B is sent but without waiting for confirmation that the first operation has been accepted in a block. Due to low gas, volume, or otherwise, the first operation is still in the mempool, and therefore the second operation has the same counter.

This causes the following error to be emitted:
```
HttpResponse: Http error response: (500) [{"kind":"temporary","id":"failure","msg":"Error while applying operation ooZofWLwKpCJWZ1Avfw4yCGS1UXaHyKjUWKSZZziEygEL9aU9K1:\nError:\n  Counter 3339520 already used for contract tz1UjBsGr8Tkogbz8fcySP6x77S5TKBvs99t (expected 3339521)\n"}]
```

### What should have happened?

We should use the batch API. No errors should be thrown.

### Steps to reproduce the bug

Try to deploy multiple contracts to a testnet. High likelihood that it will fail.

### Relevant log output

```shell
{
  errCode: 'E_ORIGINATE',
  errMsg: "Could not originate hello-tacos-one.tz on the network 'hangzhounet'",
  previous: HttpResponse: Http error response: (500) [{"kind":"temporary","id":"failure","msg":"Error while applying operation ooZofWLwKpCJWZ1Avfw4yCGS1UXaHyKjUWKSZZziEygEL9aU9K1:\nError:\n  Counter 3339520 already used for contract tz1UjBsGr8Tkogbz8fcySP6x77S5TKBvs99t (expected 3339521)\n"}]
  
      at XMLHttpRequest.request.onload (/Users/mweichert/Projects/taqueria/node_modules/@taquito/http-utils/dist/taquito-http-utils.umd.js:430:30)
      at XMLHttpRequestEventTarget.dispatchEvent (/Users/mweichert/Projects/taqueria/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:22)
      at XMLHttpRequest._dispatchProgress (/Users/mweichert/Projects/taqueria/node_modules/xhr2-cookies/dist/xml-http-request.js:358:14)
      at XMLHttpRequest._onHttpResponseEnd (/Users/mweichert/Projects/taqueria/node_modules/xhr2-cookies/dist/xml-http-request.js:319:14)
      at IncomingMessage.<anonymous> (/Users/mweichert/Projects/taqueria/node_modules/xhr2-cookies/dist/xml-http-request.js:289:61)
      at IncomingMessage.emit (node:events:377:35)
      at endReadableNT (node:internal/streams/readable:1312:12)
      at processTicksAndRejections (node:internal/process/task_queues:83:21) {
    status: 500,
    statusText: 'Internal Server Error',
    body: '[{"kind":"temporary","id":"failure","msg":"Error while applying operation ooZofWLwKpCJWZ1Avfw4yCGS1UXaHyKjUWKSZZziEygEL9aU9K1:\\nError:\\n  Counter 3339520 already used for contract tz1UjBsGr8Tkogbz8fcySP6x77S5TKBvs99t (expected 3339521)\\n"}]\n',
    url: 'https://hangzhounet.api.tez.ie/injection/operation'
  }
}
```
```


### Screenshots and images

Screenshot and images

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hu3man** [comment]
Re-opening to track investigation and fix for ongoing issues

**Comment by alexzbusko** [comment]
@mweichert @hu3man I have tried this again on main and am not running into any issues with deploying multiple contracts to a test net. I am going to close this issue
