### ISSUE TITLE
[Bug]: Running `taq compile` with an empty `/contracts` dir on WSL with an old version of NPM results in ugly, non-actionable error

### ISSUE THREAD

**Issue by hu3man** [ecadlabs/taqueria#634]
### What happened?

Running `taq compile` for the first time on WSL with a docker installation error, the following output is given to the user:

### What should have happened?

A friendly error message letting the user know that Taqueria was unable to connect to docker

### Steps to reproduce the bug

Steps to reproduce the error

### Relevant log output

```shell
taq compile
/home/zainen/code/test-taqueria/node_modules/@taqueria/node-sdk/index.js:3
`)}function Sp(e){return fe(e)||Mt(e)||!!(Pa&&e&&e[Pa])}function st(e,n){var s=typeof e;return n=n??Qe,!!n&&(s=="number"||s!="symbol"&&Wh.test(e))&&e>-1&&e%1==0&&e<n}function an(e,n,s){if(!Te(s))return!1;var a=typeof n;return(a=="number"?fn(s)&&st(n,s.length):a=="string"&&n in s)?Wn(s[n],e):!1}function pu(e,n){if(fe(e))return!1;var s=typeof e;return s=="number"||s=="symbol"||s=="boolean"||e==null||yn(e)?!0:Ah.test(e)||!xh.test(e)||n!=null&&e in ke(n)}function Bp(e){var n=typeof e;return n=="string"||n=="number"||n=="symbol"||n=="boolean"?e!=="_proto_":e===null}function Du(e){var n=Ai(e),s=h[n];if(typeof s!="function"||!(n in ye.prototype))return!1;if(e===s)return!0;var a=hu(s);return!!a&&e===a[0]}function Pp(e){return!!Oa&&Oa in e}var Ip=ri?ut:Iu;function Br(e){var n=e&&e.constructor,s=typeof n=="function"&&n.prototype||Jt;return e===s}function Ol(e){return e===e&&!Te(e)}function kl(e,n){return function(s){return s==null?!1:s[e]===
SyntaxError: Unexpected token ?
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/zainen/code/test-taqueria/node_modules/@taqueria/plugin-ligo/index.js:1:32)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
taq [command]
Commands:
  taq init [projectDir]                     Initialize a new project
  taq scaffold [scaffoldUrl] [scaffoldProj  Generate a new project using pre-mad
  ectDir]                                   e scaffold
Options:
      --version     Show version number                                [boolean]
      --build       Display build information about the current version[boolean]
  -p, --projectDir  Path to your project directory               [default: "./"]
      --configDir   Config directory (default ./.taq)        [default: "./.taq"]
  -e, --env         Specify an environment configuration
Taqueria is currently in BETA. You've been warned. :)
Cannot read properties of undefined (reading 'version')
```
```


### Screenshots and images

Screenshot and images

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hu3man** [comment]
Closing: part of #107
