### ISSUE TITLE
[Bug]: taq test is returning a 0 exit code even though tests are failing

### ISSUE THREAD

**Issue by alexzbusko** [ecadlabs/taqueria#988]
### What happened?

When running a test through the taq test command it will exit with a code of 0 even if tests fail which makes for a bad experience in CI runners since they will interpret that as a success. 

### What should have happened?

When tests fail it should make the jest plugin return a non-zero code

### Steps to reproduce the bug

Steps to reproduce the error:

1. Initialize a taq project
2. Install the jest plugin
3. Initialize the tests directory with `taq test -i`
4. Add a test that will fail in the tests directory with a name like `failing-test.spec.ts`:
```
describe('dummy test for jest plugin testing', () => {
	test('fail', () => {
		expect(1).toEqual(2);
	});
});
```
5. Run the test and check the exit code afterwards with `echo $?`

### Relevant log output

```shell
$ taq test
 FAIL  tests/test1.spec.ts
  dummy test for jest plugin testing
    ✕ 1 test for jest (9 ms)

  ● dummy test for jest plugin testing › 1 test for jest

    error: Error: expect(received).toEqual(expected) // deep equality

    Expected: 2
    Received: 1

      4 |                       expect(1).toEqual(2);
      5 |               } catch (error) {
    > 6 |                       throw new Error(`error: ${error}`);
        |                             ^
      7 |               }
      8 |       });
      9 | });

      at Object.<anonymous> (test1.spec.ts:6:10)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        0.529 s
Ran all test suites.
alexander@alexander:~/taqueria/alex-1$ echo $?
0




JEST PLUGIN EXIT CODE*****************************************:
$ npx jest test.spec.ts 
 FAIL  ./test.spec.ts
  dummy test for jest plugin testing
    ✕ fail (2 ms)

  ● dummy test for jest plugin testing › fail

    expect(received).toEqual(expected) // deep equality

    Expected: 2
    Received: 1

      1 | describe('dummy test for jest plugin testing', () => {
      2 |       test('fail', () => {
    > 3 |               expect(1).toEqual(2);
        |                         ^
      4 |       });
      5 | });
      6 |

      at Object.toEqual (test.spec.ts:3:13)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        0.491 s
Ran all test suites matching /test.spec.ts/i.
alexander@alexander:~/taqueria$ echo $?
1
```

### Screenshots and images

Screenshot and images

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by russellmorton** [comment]
@alexzbusko please verify.

**Comment by alexzbusko** [comment]
@russellmorton the taqueria binary is now reporting a non-zero exit code when tests fail
